package modelo;
// Generated 9/04/2018 11:24:07 PM by Hibernate Tools 4.3.1



/**
 * CodigoVerificacionDe generated by hbm2java
 */
public class CodigoVerificacionDe  implements java.io.Serializable {


     private int idCodigoVerificacion;
     private String codigoVerificacion;
     private Integer fkUsuario;

    public CodigoVerificacionDe() {
    }

	
    public CodigoVerificacionDe(int idCodigoVerificacion) {
        this.idCodigoVerificacion = idCodigoVerificacion;
    }
    
    public CodigoVerificacionDe(int idCodigoVerificacion, String codigoVerificacion, Integer fkUsuario) {
       this.idCodigoVerificacion = idCodigoVerificacion;
       this.codigoVerificacion = codigoVerificacion;
       this.fkUsuario = fkUsuario;
    }
   
    public CodigoVerificacionDe(String codigoVerificacion, Integer fkUsuario) {
       this.codigoVerificacion = codigoVerificacion;
       this.fkUsuario = fkUsuario;
    }
    
    public int getIdCodigoVerificacion() {
        return this.idCodigoVerificacion;
    }
    
    public void setIdCodigoVerificacion(int idCodigoVerificacion) {
        this.idCodigoVerificacion = idCodigoVerificacion;
    }
    public String getCodigoVerificacion() {
        return this.codigoVerificacion;
    }
    
    public void setCodigoVerificacion(String codigoVerificacion) {
        this.codigoVerificacion = codigoVerificacion;
    }
    public Integer getFkUsuario() {
        return this.fkUsuario;
    }
    
    public void setFkUsuario(Integer fkUsuario) {
        this.fkUsuario = fkUsuario;
    }




}


