package modelo;
// Generated 9/04/2018 11:24:07 PM by Hibernate Tools 4.3.1


/**
 * ComentarioEn generated by hbm2java
 */
public class ComentarioEn  implements java.io.Serializable {


     private int idComentarioEn;
     private Comentario comentario;
     private Pregunta pregunta;
     private Usuario usuario;

    public ComentarioEn() {
    }

    public ComentarioEn(int idComentarioEn) {
        this.idComentarioEn = idComentarioEn;
    }
    
    public ComentarioEn(int idComentarioEn, Comentario comentario, Pregunta pregunta, Usuario usuario) {
       this.idComentarioEn = idComentarioEn;
       this.comentario = comentario;
       this.pregunta = pregunta;
       this.usuario = usuario;
    }
    
    public ComentarioEn(Comentario comentario, Pregunta pregunta, Usuario usuario){
        this.comentario = comentario;
        this.pregunta = pregunta;
        this.usuario = usuario;        
    }
   
    public int getIdComentarioEn() {
        return this.idComentarioEn;
    }
    
    public void setIdComentarioEn(int idComentarioEn) {
        this.idComentarioEn = idComentarioEn;
    }
    public Comentario getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Comentario comentario) {
        this.comentario = comentario;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }





}


